# --- Game Window Constants ---
WINDOW_WIDTH = 800
WINDOW_HEIGHT = 600

# --- Game Object Dimensions ---
SPACESHIP_WIDTH = 180
SPACESHIP_HEIGHT = 180
ENEMY_WIDTH = 100
ENEMY_HEIGHT = 80
FIREBALL_WIDTH = 40
FIREBALL_HEIGHT = 40

# --- Movement Settings ---
ENEMY_X_CHANGE = 24
ENEMY_Y_CHANGE = 10
SPACESHIP_MOVE_STEP = 25
FIREBALL_Y_STEP = 40

# --- Game Settings ---
NUM_OF_ENEMIES = 6
MAX_SPACESHIP_X = WINDOW_WIDTH - SPACESHIP_WIDTH
MAX_FIREBALL_Y = 0
GAME_OVER_Y_THRESHOLD = 360
CLOCK_TICK_RATE = 40

# --- Colors ---
COLOR_BLACK = (0, 0, 0)
COLOR_WHITE = (255, 255, 255)